language: ruby
os: linux
dist: xenial
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
  latex-beamer git
- git clone https://github.com/matze/mtheme.git
- cd mtheme
- make sty
- cp *.sty ../
- cd ../
script:
- pdflatex Simpsons-IT.tex
- pdflatex Simpsons-IT.tex
- pdflatex Simpsons-IT_article.tex
- pdflatex Simpsons-IT_article.tex
- pdflatex Simpsons-IT_FF_Edition.tex
- pdflatex Simpsons-IT_FF_Edition.tex
- pdflatex Simpsons-IT_FF_Edition_article.tex
- pdflatex Simpsons-IT_FF_Edition_article.tex
deploy:
  provider: releases
  file:
  - Simpsons-IT.pdf
  - Simpsons-IT_article.pdf
  - Simpsons-IT_FF_Edition.pdf
  - Simpsons-IT_FF_Edition_article.pdf
  cleanup: true
  draft: false
  prerelease: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
    repo: mflingelli/Simpsons-IT
    branch: master
  api_key:
    secure: blBTgiiszH/lEs6l3Y4slXBjIAowurwIPKizNhjCV9oOBCYmKVIfGMRA/rrzSSyo+/4oyfZTB0Mxd6Z3ajbLHboSZJBmO9of2wsMGSigGedGdNVJsXoacr8RUoVj1KJ0fKh7dh+VAWF8WHFuiIuhD9eLjX6r0GhTItN7nKptSH3Sy/4p/1Em2V6sL1VU7PquBGqQLxeJ4PcIENKKZT1mZJnohXld7upMRhRf16aPSblN6C2kb2kaipudMkxjOOq2cq9YMlCrP10yHfY+vsUgxgGpuPFukuPxlKjDdzceEgKeTRIVRBLqfe2hsRvB0FEG+jYc2FXc6/eOmdQWcIfW3kbtoWUcTOvsrE4vvewdKO10Np0dn0JjC2y7wRhF1e3AFc/NrDYelPY6Htk+Acwne6NZwWtm1AhDd8WJOfTkwVv3EFNZHw84F9cBSYJZqG5//jAjA967ySTpvTX13VChI8l3iiPWPZROwjJoL2VQAamxYhuV8JRdXw1weBfas6/tfW946z0BV5ztiKcN/pMRAkA92xUBZNzG2sxMdW6P3hbeBXZn+vVUd6nR7aX6W6abw5w84QHX3fvdWl4FzsjRrIr9D7gwDe4Y6eXmY6BG9/zTNNfAykb7+UFsZdMTuu1XYbzraevDp37KzuuGoodnIjRfT8Y9wgioW/72o5qilB0=
