name: Simpsons-IT
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TeXLive installation
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german latex-beamer git
      - name: Prepartion of mtheme
        run: |
          git clone https://github.com/matze/mtheme.git
          cd mtheme
          make sty
          cp *.sty ../
          cd ../
      - name: LaTeX compilation
        run: |
          pdflatex Simpsons-IT.tex
          pdflatex Simpsons-IT.tex
          pdflatex Simpsons-IT_article.tex
          pdflatex Simpsons-IT_article.tex
          pdflatex Simpsons-IT_FF_Edition.tex
          pdflatex Simpsons-IT_FF_Edition.tex
          pdflatex Simpsons-IT_FF_Edition_article.tex
          pdflatex Simpsons-IT_FF_Edition_article.tex
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            Simpsons-IT.pdf
            Simpsons-IT_article.pdf
            Simpsons-IT_FF_Edition.pdf
            Simpsons-IT_FF_Edition_article.pdf


